name: torch-splatting
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - cuda-toolkit #install nvcc to build simple-knn
  - python=3.11
  - pytorch
  - pytorch-cuda
  - pip
  # - torchaudio
  # - torchvision
  #  - pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
  - pip:
      - accelerate
      - einops
      - imageio
      - matplotlib
      - sympy
      - ipywidgets
      - ipykernel
      - ipython-autotime
      # - submodules/simple-knn
      # Instad, do: pip install git+https://github.com/camenduru/simple-knn
      # Or: pip install submodules/simple-knn
      
